"""Reproduce county/district/code lookup from official pages linked by2025 IT201 instructions."""
import ast
import json,re,html,hashlib,sys
from pathlib import Path
root=Path(__file__).parent;rows=[]
for source in json.loads((root/'manifest.json').read_text()):
 data=(root/source['file']).read_bytes();assert hashlib.sha256(data).hexdigest()==source['documentHash']
 assert source['url'].startswith('https://www.tax.ny.gov/pit/file/school_district/')
 if source['file']=='nyc.htm':continue
 text=data.decode();header=re.search(r'<h1[^>]*>(.*?)</h1>',text,re.S)[1]
 county=html.unescape(re.sub('<[^>]+>','',header)).strip();county=re.split(r' - | – ',county)[-1];county=re.sub(r'\s*\([^)]*\)| County','',county).strip()
 county={'Brooklyn':'Kings','Manhattan':'New York','Staten Island':'Richmond'}.get(county,county)
 for table in re.findall(r'<table\b.*?</table>',text,re.S):
  for row in re.findall(r'<tr\b[^>]*>(.*?)</tr>',table,re.S):
   cells=[html.unescape(re.sub('<[^>]+>','',cell)).strip() for cell in re.findall(r'<td\b[^>]*>(.*?)</td>',row,re.S)]
   if len(cells)==2 and re.fullmatch(r'\d{3}',cells[1]):rows.append(dict(county=county,district=' '.join(cells[0].split()),code=cells[1],sourceHash=source['documentHash'],url=source['url']))
rows=sorted(rows,key=lambda row:(row['county'],row['code'],row['district'],row['url']))
seen=set();rows=[row for row in rows if not ((key:=(row['county'],row['district'],row['code'])) in seen or seen.add(key))]
assert len(set(row['county'] for row in rows))==62
file=root.parent.parent/'school-district-data.ts'
if '--write' in sys.argv:file.write_text('// Generated by sources/school-districts/verify.py from pinned official county pages.\nexport const NY_SCHOOL_DISTRICTS = '+json.dumps(rows)+' as const;\n')
else:
 text=file.read_text();obj=text[text.index('=')+1:text.rindex(' as const;')];obj=re.sub(r'\b(county|district|code|sourceHash|url)\s*:',r'"\1":',obj);obj=re.sub(r',\s*([}\]])',r'\1',obj);assert ast.literal_eval(obj)==rows
print(str(len(rows))+' district/county codes across62 counties verified')
