"""Reproduce single NYS/NYC tables from pinned official HTML; no marginal-rate replacement."""
import hashlib, json, re, html, sys
from pathlib import Path
root=Path(__file__).parent
for item in json.loads((root/'manifest.json').read_text()):
 assert hashlib.sha256((root/item['file']).read_bytes()).hexdigest()==item['documentHash']
 assert item['url'].startswith('https://www.tax.ny.gov/')
tables={}
for table in re.findall(r'<table\b[^>]*>.*?</table>',(root/'tables.html').read_text(),re.S):
 caption=re.search(r'<caption[^>]*>(.*?)</caption>',table,re.S)
 if not caption:continue
 name=html.unescape(re.sub('<[^>]+>','',caption[1])).strip()
 key='state' if name=='New York State Tax Table' else 'city' if name=='New York City Tax Table' else None
 if not key:continue
 rows=[]
 for tr in re.findall(r'<tr\b[^>]*>(.*?)</tr>',table,re.S):
  cells=[html.unescape(re.sub('<[^>]+>','',td)).strip().replace(',','').replace('$','') for td in re.findall(r'<td\b[^>]*>(.*?)</td>',tr,re.S)]
  if len(cells)==5 and all(c.isdigit() for c in cells):rows.append([int(cells[i]) for i in [0,1,2]])
 tables.setdefault(key,[]).extend(rows)
assert set(tables)=={'state','city'}
for rows in tables.values():
 assert rows[0][0]==0 and rows[-1][1]==65000
 assert all(a[1]==b[0] for a,b in zip(rows,rows[1:]))
encoded=json.dumps(tables,separators=(',',':'))
p=root.parent/'tables-data.ts'
if '--write' in sys.argv:p.write_text('// Generated by sources/verify.py --write from pinned official tables.\nexport const NY_2025_SINGLE_TABLES = '+encoded+' as const;\n')
else:
 match=re.search(r'=\s*(\{.*\})\s*as const;',p.read_text(),re.S)
 assert match
 normalized=re.sub(r'\b(state|city)\s*:',r'"\1":',match[1])
 normalized=re.sub(r',\s*([}\]])',r'\1',normalized)
 assert json.loads(normalized)==tables
print(str(len(json.loads((root/'manifest.json').read_text())))+' NY source captures and '+str(sum(map(len,tables.values())))+' NYS/NYC single table rows verified')
