import { MEXICO_2025_INVESTMENT_REFERENCE_IDS } from './investments.js';
import { deepFreeze } from '@emdo/contracts';

/**
 * Source-bound applicability for the fields that this candidate can either
 * calculate, transfer from a reviewed fact, or deliberately leave unresolved.
 * `formId` is the stable package identifier; `satSection` and `satLabel` keep
 * the mapping to the SAT application visible without pretending that an
 * internal working-paper key is an electronic filing field name.
 */
export type Mexico2025FieldStatus =
  'implemented' | 'explicit-zero' | 'review-required' | 'unsupported';

export type Mexico2025FieldApplicability = {
  id: string;
  taxpayerType: 'individual' | 'sole-proprietor' | 'corporation';
  formId: string;
  satSection: string;
  fieldKey: string;
  satLabel: string;
  valueType: 'money' | 'boolean' | 'text';
  status: Mexico2025FieldStatus;
  sourceReferenceIds: readonly string[];
  sourceLocator: string;
  requiredFactKeys: readonly string[];
  ruleId: string | null;
  emittedByEvaluator: boolean;
};

const salaryRefs = [
  'sat-mx-2025-declaracion-anual-personas',
  'sat-mx-2025-guia-sueldos-salarios',
  'sat-mx-anexo8-rmf-2025',
  'sat-mx-lisr-articulo-90',
  'sat-mx-lisr-articulo-93',
  'sat-mx-lisr-articulo-94',
  'sat-mx-lisr-articulo-96',
  'sat-mx-lisr-articulo-97',
  'sat-mx-lisr-articulo-151',
  'sat-mx-lisr-articulo-152',
  'sat-mx-2025-subsidio-empleo',
  'dof-mx-2025-uma',
] as const;
const professionalRefs = [
  'sat-mx-2025-declaracion-anual-personas',
  'sat-mx-2025-guia-actividad-profesional',
  'sat-mx-anexo8-rmf-2025',
  'sat-mx-lisr-articulo-90',
  'sat-mx-lisr-articulo-100',
  'sat-mx-lisr-articulo-102',
  'sat-mx-lisr-articulo-103',
  'sat-mx-lisr-articulo-105',
  'sat-mx-lisr-articulo-106',
  'sat-mx-lisr-articulo-109',
  'sat-mx-lisr-articulo-151',
  'sat-mx-lisr-articulo-152',
  'dof-mx-2025-uma',
] as const;
const corporateRefs = [
  'sat-mx-2025-declaracion-anual-empresas',
  'sat-mx-2025-guia-personas-morales-regimen-general',
  'sat-mx-lisr-articulo-9',
  'sat-mx-lisr-articulo-14',
  'sat-mx-lisr-articulo-25',
  'sat-mx-lisr-articulo-27',
  'sat-mx-lisr-articulo-44',
  'sat-mx-lisr-articulo-76',
  'sat-mx-lisr-articulo-77',
] as const;

const rule = (formId: string, fieldKey: string) =>
  `mx2025.${formId}.${fieldKey}`;

function field(
  taxpayerType: Mexico2025FieldApplicability['taxpayerType'],
  formId: string,
  satSection: string,
  fieldKey: string,
  satLabel: string,
  valueType: Mexico2025FieldApplicability['valueType'],
  status: Mexico2025FieldStatus,
  sourceReferenceIds: readonly string[],
  sourceLocator: string,
  requiredFactKeys: readonly string[] = [],
): Mexico2025FieldApplicability {
  return {
    id: `${taxpayerType}.${formId}.${fieldKey}`,
    taxpayerType,
    formId,
    satSection,
    fieldKey,
    satLabel,
    valueType,
    status,
    sourceReferenceIds,
    sourceLocator,
    requiredFactKeys,
    ruleId:
      status === 'unsupported' || status === 'review-required'
        ? null
        : rule(formId, fieldKey),
    emittedByEvaluator: status === 'implemented' || status === 'explicit-zero',
  };
}

const salaryAnnual = 'SAT annual persons-físicas determination';
const salaryIncome =
  'SAT annual persons-físicas sueldos, salarios y asimilados';
const professionalIncome =
  'SAT annual persons-físicas actividad empresarial y servicios profesionales';
const corporateIncome = 'SAT annual persons-morales Régimen General / Ingresos';
const corporateDeductions =
  'SAT annual persons-morales Régimen General / Deducciones autorizadas';
const corporateDetermination =
  'SAT annual persons-morales Régimen General / Determinación';

/**
 * This catalog intentionally includes the unresolved branches visible in the
 * current SAT guides.  A field marked unsupported is an explicit applicability
 * result and is never emitted as a zero by the evaluator.
 */
export const MEXICO_2025_FIELD_APPLICABILITY = deepFreeze([
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'annualIncome',
    'Ingreso anual',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Ingreso anual',
    ['salary.annualIncome'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'exemptIncome',
    'Ingresos exentos',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Ingresos exentos',
    ['salary.exemptIncome'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'accumulatedIncome',
    'Ingresos acumulables',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Ingresos acumulables',
    ['salary.annualIncome', 'salary.exemptIncome'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'nonAccumulatingIncome',
    'Ingresos no acumulables',
    'money',
    'unsupported',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Ingresos no acumulables',
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'employmentSubsidy',
    'Subsidio para el empleo',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Subsidio para el empleo',
    ['salary.employmentSubsidy'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'incomeTaxWithheld',
    'Impuesto retenido',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, income section: Impuesto retenido',
    ['salary.isrWithheld'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'localIncomeTax',
    'Impuesto local a los ingresos por salarios',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-96', 'sat-mx-2025-guia-sueldos-salarios'],
    'LISR article 96: local salary-income tax deduction input; annual salary guide income section',
    ['salary.localIncomeTax'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'personalDeductionsOther',
    'Deducciones personales distintas del impuesto local',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'sat-mx-2025-guia-sueldos-salarios'],
    'LISR article 151 and annual salary guide personal-deductions section',
    ['personalDeductions.amount'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'personalDeductionsTotal',
    'Total de deducciones personales consideradas',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'sat-mx-lisr-articulo-96'],
    'LISR articles 151 and 96: reviewed personal deductions plus eligible local salary tax',
    ['personalDeductions.amount', 'salary.localIncomeTax'],
  ),
  field(
    'individual',
    'SUELDOS',
    salaryIncome,
    'provisionalPayments',
    'Pagos provisionales',
    'money',
    'implemented',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-97'],
    'Annual salary guide determination: total provisional payments; bounded slice requires explicit zero',
    ['salary.provisionalPayments'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'accumulatedIncome',
    'Ingresos acumulables',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, annual determination: Ingresos acumulables',
    ['salary.annualIncome', 'salary.exemptIncome', 'otherChapterIncome'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'personalDeductionsClaimed',
    'Deducciones personales',
    'money',
    'implemented',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-151'],
    'GuiaLlenado_SueldosSalarios.pdf, annual determination: Deducciones personales',
    ['personalDeductions.amount', 'salary.localIncomeTax'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'personalDeductionsAllowed',
    'Deducciones personales permitidas',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'dof-mx-2025-uma'],
    'LISR article 151 and DOF 2025 UMA: lesser-of cap result',
    ['personalDeductions.amount', 'salary.annualIncome', 'otherChapterIncome'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'personalDeductionCap',
    'Límite de deducciones personales',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'dof-mx-2025-uma'],
    'LISR article 151: lesser-of five annual UMA or 15% total-income cap',
    ['salary.annualIncome', 'otherChapterIncome'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'otherChapterIncome',
    'Ingresos de otros capítulos',
    'money',
    'explicit-zero',
    ['sat-mx-2025-declaracion-anual-personas', 'sat-mx-lisr-articulo-152'],
    'Annual return other-Title-IV income gate; explicit zero is required for this slice',
    ['otherChapterIncome'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'otherCredits',
    'Otros acreditamientos',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-152'],
    'Annual salary guide determination: other credits; bounded slice requires explicit zero',
    ['foreignTaxCredit', 'annualOtherCredits'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'provisionalPayments',
    'Pagos provisionales efectuados',
    'money',
    'implemented',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-97'],
    'Annual salary guide determination: payments made; bounded salary slice requires explicit zero',
    ['salary.provisionalPayments'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'isrWithheld',
    'ISR retenido',
    'money',
    'implemented',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-97'],
    'Annual salary guide determination: ISR withheld',
    ['salary.isrWithheld'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'taxableBase',
    'Base gravable',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-152', 'sat-mx-anexo8-rmf-2025'],
    'LISR article 152 and Anexo 8 section C(II): annual base',
    ['salary.annualIncome', 'salary.exemptIncome', 'personalDeductions.amount'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'personalDeductionCategoryDetail',
    'Detalle de deducciones personales por categoría',
    'money',
    'review-required',
    ['sat-mx-2025-guia-sueldos-salarios', 'sat-mx-lisr-articulo-151'],
    'GuiaLlenado_SueldosSalarios.pdf, personal-deductions category detail',
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'isrAnnual',
    'ISR del ejercicio',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-152', 'sat-mx-anexo8-rmf-2025'],
    'LISR article 152 and Anexo 8 section C(II): annual tariff',
    ['salary.annualIncome', 'salary.exemptIncome', 'personalDeductions.amount'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'employmentSubsidy',
    'Subsidio para el empleo acreditable',
    'money',
    'implemented',
    ['sat-mx-2025-subsidio-empleo', 'sat-mx-2025-guia-sueldos-salarios'],
    'Annual salary guide determination: employment subsidy amount',
    ['salary.employmentSubsidy'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'employmentSubsidyApplied',
    'Subsidio para el empleo aplicado',
    'money',
    'implemented',
    ['sat-mx-2025-subsidio-empleo', 'sat-mx-2025-guia-sueldos-salarios'],
    'GuiaLlenado_SueldosSalarios.pdf, annual determination: Subsidio applied',
    ['salary.employmentSubsidy', 'salary.subsidyEligible'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'credits',
    'Acreditamientos',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-97', 'sat-mx-lisr-articulo-152'],
    'LISR articles 97 and 152: withholding, subsidy and provisional-payment credits',
    [
      'salary.isrWithheld',
      'salary.employmentSubsidy',
      'salary.provisionalPayments',
    ],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'taxDue',
    'Impuesto a cargo del ejercicio',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, annual determination: Impuesto a cargo',
    ['salary.isrWithheld'],
  ),
  field(
    'individual',
    'DECLARACION_ANUAL',
    salaryAnnual,
    'balanceFavor',
    'Saldo a favor del ejercicio',
    'money',
    'implemented',
    salaryRefs,
    'GuiaLlenado_SueldosSalarios.pdf, annual determination: Saldo a favor',
    ['salary.isrWithheld'],
  ),

  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'grossReceipts',
    'Ingresos cobrados',
    'money',
    'implemented',
    professionalRefs,
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, income section',
    ['business.grossReceipts'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'refundsDiscounts',
    'Devoluciones, descuentos y bonificaciones',
    'money',
    'implemented',
    professionalRefs,
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, income section',
    ['business.refundsDiscounts'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'netReceipts',
    'Ingresos netos cobrados',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-102'],
    'LISR article 102 and annual professional guide: effectively received income less returns and discounts',
    ['business.grossReceipts', 'business.refundsDiscounts'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'authorizedDeductions',
    'Deducciones autorizadas',
    'money',
    'implemented',
    professionalRefs,
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, authorized deductions section',
    ['business.authorizedDeductions'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'localIncomeTax',
    'Impuesto local sobre los ingresos',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-103', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 103 and annual professional guide: local income tax authorized deduction',
    ['business.localIncomeTax'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'fiscalUtilityBeforePtu',
    'Utilidad fiscal antes de PTU',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-109', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 109 and annual professional guide determination: income less authorized deductions and local tax',
    [
      'business.grossReceipts',
      'business.refundsDiscounts',
      'business.authorizedDeductions',
      'business.localIncomeTax',
    ],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'ptuPaid',
    'PTU pagada en el ejercicio',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-109', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 109 and annual professional guide determination: PTU paid',
    ['business.ptuPaid'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'utilityAfterPtu',
    'Utilidad fiscal después de PTU',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-109', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 109: utility after PTU paid',
    ['business.ptuPaid'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'priorLossesApplied',
    'Pérdidas fiscales de ejercicios anteriores aplicadas',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-109', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 109 and annual professional guide determination: prior losses applied',
    ['business.priorLossesApplied'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'investmentDeductions',
    'Deducción de inversiones',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-103'],
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, investment schedule',
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'taxableUtility',
    'Utilidad fiscal gravable',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-109', 'sat-mx-lisr-articulo-152'],
    'LISR articles 109 and 152: utility after PTU and losses',
    [
      'business.grossReceipts',
      'business.authorizedDeductions',
      'business.ptuPaid',
    ],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'otherAccruedIncome',
    'Otros ingresos acumulables',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-100'],
    'Annual professional guide income section: other income; bounded slice requires explicit zero',
    ['business.otherAccruedIncome'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'taxStimuli',
    'Estímulos fiscales',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-109'],
    'Annual professional guide determination: tax stimuli; bounded slice requires explicit zero',
    ['business.taxStimuli'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'accumulatedIncome',
    'Ingresos acumulables de la actividad',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-109'],
    'Annual professional guide determination: accumulated activity income after utility and other-income gate',
    ['business.otherAccruedIncome'],
  ),
  field(
    'sole-proprietor',
    'ACTIVIDAD_PROFESIONAL',
    professionalIncome,
    'monthlyProvisionalPaymentSchedule',
    'Pagos provisionales mensuales',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-106'],
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, provisional-payment detail',
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'otherChapterIncome',
    'Ingresos de otros capítulos',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual determination other-Title-IV income gate; bounded professional slice requires explicit zero',
    ['otherChapterIncome'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'accumulatedIncome',
    'Ingresos acumulables',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual professional guide determination: accumulated income',
    ['business.grossReceipts', 'business.authorizedDeductions'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'personalDeductionsClaimed',
    'Deducciones personales',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-151'],
    'Annual professional guide determination: personal deductions claimed',
    ['personalDeductions.amount'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'personalDeductionsAllowed',
    'Deducciones personales permitidas',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'dof-mx-2025-uma'],
    'LISR article 151 and DOF 2025 UMA: lesser-of cap result',
    ['personalDeductions.amount', 'business.grossReceipts'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'personalDeductionCap',
    'Límite de deducciones personales',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-151', 'dof-mx-2025-uma'],
    'LISR article 151: lesser-of five annual UMA or 15% total-income cap',
    ['business.grossReceipts', 'otherChapterIncome'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'otherCredits',
    'Otros acreditamientos',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual professional guide determination: other credits; bounded slice requires explicit zero',
    ['foreignTaxCredit', 'annualOtherCredits'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'provisionalPayments',
    'Pagos provisionales efectuados',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-106'],
    'Annual professional guide determination: provisional payments',
    ['business.provisionalPayments'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'isrWithheld',
    'ISR retenido',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-106'],
    'Annual professional guide determination: ISR withheld by legal entities',
    ['business.legalEntityWithholding'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'credits',
    'Acreditamientos',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual professional guide determination: total reviewed credits',
    ['business.provisionalPayments', 'business.legalEntityWithholding'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'taxDue',
    'Impuesto a cargo del ejercicio',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual professional guide determination: tax due',
    ['business.provisionalPayments', 'business.legalEntityWithholding'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    salaryAnnual,
    'balanceFavor',
    'Saldo a favor del ejercicio',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-152'],
    'Annual professional guide determination: balance in favor',
    ['business.provisionalPayments', 'business.legalEntityWithholding'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    professionalIncome,
    'professionalPaymentsFromLegalEntities',
    'Pagos por servicios profesionales efectuados por personas morales',
    'money',
    'implemented',
    ['sat-mx-2025-guia-actividad-profesional', 'sat-mx-lisr-articulo-106'],
    'Annual professional guide withholding detail: legal-entity professional payments',
    ['business.professionalPaymentsFromLegalEntities'],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    professionalIncome,
    'taxableBase',
    'Base gravable',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-152', 'sat-mx-anexo8-rmf-2025'],
    'LISR article 152 and Anexo 8 section C(II): annual base',
    [
      'business.grossReceipts',
      'business.authorizedDeductions',
      'personalDeductions.amount',
    ],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    professionalIncome,
    'isrAnnual',
    'ISR del ejercicio',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-152', 'sat-mx-anexo8-rmf-2025'],
    'LISR article 152 and Anexo 8 section C(II): annual tariff',
    [
      'business.grossReceipts',
      'business.authorizedDeductions',
      'business.ptuPaid',
    ],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    professionalIncome,
    'professionalWithholding',
    'ISR retenido por personas morales',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-106', 'sat-mx-2025-guia-actividad-profesional'],
    'LISR article 106: 10% withholding on professional-service payments',
    [
      'business.professionalPaymentsFromLegalEntities',
      'business.legalEntityWithholding',
    ],
  ),
  field(
    'sole-proprietor',
    'DECLARACION_ANUAL_PROFESIONAL',
    professionalIncome,
    'balanceSheet',
    'Estado de posición financiera',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-actividad-profesional'],
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, balance-sheet section',
  ),
  field(
    'individual',
    'PAGO',
    'SAT annual persons-físicas / Pago',
    'taxDue',
    'Impuesto a cargo',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-sueldos-salarios',
      'sat-mx-2025-declaracion-anual-personas',
    ],
    'GuiaLlenado_SueldosSalarios.pdf, payment section',
    ['salary.isrWithheld'],
  ),
  field(
    'individual',
    'PAGO',
    'SAT annual persons-físicas / Pago',
    'balanceFavor',
    'Saldo a favor',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-sueldos-salarios',
      'sat-mx-2025-declaracion-anual-personas',
    ],
    'GuiaLlenado_SueldosSalarios.pdf, payment section',
    ['salary.isrWithheld'],
  ),
  field(
    'sole-proprietor',
    'PAGO',
    'SAT annual persons-físicas / Pago',
    'taxDue',
    'Impuesto a cargo',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-actividad-profesional',
      'sat-mx-2025-declaracion-anual-personas',
    ],
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, payment section',
    ['business.provisionalPayments', 'business.legalEntityWithholding'],
  ),
  field(
    'sole-proprietor',
    'PAGO',
    'SAT annual persons-físicas / Pago',
    'balanceFavor',
    'Saldo a favor',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-actividad-profesional',
      'sat-mx-2025-declaracion-anual-personas',
    ],
    'GuiaLlenado_ActividadesEmpresarialesProfesionales2025.pdf, payment section',
    ['business.provisionalPayments', 'business.legalEntityWithholding'],
  ),

  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'averageAnnualCredits',
    'Saldo promedio anual de créditos',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-44'],
    'Article 44 I: sum of 12 month-end balances divided by 12; Articles 45/46 classification reviewed',
    Array.from(
      { length: 12 },
      (_, i) =>
        `corporation.inflation.${String(i + 1).padStart(2, '0')}.credits`,
    ),
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'averageAnnualDebts',
    'Saldo promedio anual de deudas',
    'money',
    'implemented',
    ['sat-mx-lisr-articulo-44'],
    'Article 44 I: sum of 12 month-end balances divided by 12; Articles 45/46 classification reviewed',
    Array.from(
      { length: 12 },
      (_, i) => `corporation.inflation.${String(i + 1).padStart(2, '0')}.debts`,
    ),
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'accruedIncome',
    'Ingresos acumulables / ingresos nominales agregados',
    'money',
    'implemented',
    corporateRefs,
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1 Ingresos',
    ['corporation.accruedIncome'],
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'refundsDiscounts',
    'Devoluciones, descuentos o bonificaciones',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-25',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1 income and Article 25(I)',
    ['corporation.refundsDiscounts'],
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'totalAccumulatedIncome',
    'Total de ingresos acumulables',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(e)',
    ['corporation.accruedIncome', 'corporation.refundsDiscounts'],
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'exemptOrNonAccumulatingIncome',
    'Ingresos exentos o no acumulables',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(a); ordinary slice requires no such income',
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'nominalIncomeDetail',
    'Ingresos nominales detallados',
    'money',
    'review-required',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(b); aggregate is accepted only as reviewed working-paper input',
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'annualInflationAdjustmentIncome',
    'Ajuste anual por inflación acumulable',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-44',
      'inegi-mx-inpc-december-2024',
      'inegi-mx-inpc-december-2025',
      'sat-mx-cff-articulo-17a',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(c); Article 44 monthly reviewed balances and pinned annual INPC factor',
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'annualOnlyIncome',
    'Ingresos que solo se acumulan en la declaración anual',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(d); ordinary slice requires no annual-only income',
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'foreignSourceIncome',
    'Ingresos procedentes de fuente ubicada en el extranjero',
    'money',
    'unsupported',
    corporateRefs,
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(d) foreign-source detail',
  ),
  field(
    'corporation',
    'INGRESOS_PERSONA_MORAL',
    corporateIncome,
    'foreignDividendIncome',
    'Ingresos del extranjero por dividendos distribuidos',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 1(d) foreign-dividend detail',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'investmentOriginalCost',
    'Monto original de las inversiones',
    'money',
    'implemented',
    MEXICO_2025_INVESTMENT_REFERENCE_IDS,
    'LISR Articles 31 and 34: supported first-year office/computer asset schedule',
    ['corporation.investments.rows'],
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'investmentUnadjustedDeduction',
    'Deducción de inversiones antes de actualización',
    'money',
    'implemented',
    MEXICO_2025_INVESTMENT_REFERENCE_IDS,
    'LISR Articles 31 and 34: supported first-year office/computer asset schedule',
    ['corporation.investments.rows'],
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'authorizedDeductions',
    'Total de deducciones autorizadas',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-25',
      'sat-mx-lisr-articulo-27',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(h); Articles 25 and 27',
    ['corporation.authorizedDeductions'],
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'salaryWagesAndAssimilates',
    'Sueldos, salarios y asimilados',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(a); payroll schedule is outside the candidate',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'expenses',
    'Gastos',
    'money',
    'review-required',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-27',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(b); expense detail and CFDI/payment proof are not itemized by this adapter',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'payrollRelatedDeductions',
    'Deducciones relacionadas con la nómina',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(c); payroll-related schedule is outside the candidate',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'annualInflationAdjustmentDeductible',
    'Ajuste anual por inflación deducible',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-44',
      'inegi-mx-inpc-december-2024',
      'inegi-mx-inpc-december-2025',
      'sat-mx-cff-articulo-17a',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(f); Article 44 monthly reviewed balances and pinned annual INPC factor',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'administrativeFacilityOrDeductibleStimulus',
    'Facilidades administrativas y estímulos deducibles',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(g); ordinary slice requires explicit zero',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'costOfSales',
    'Costo de lo vendido',
    'money',
    'unsupported',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-25',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(e)',
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'investmentDeductions',
    'Deducción de inversiones',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-25',
      ...MEXICO_2025_INVESTMENT_REFERENCE_IDS,
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(d); Articles 31 and 34, first-year office/computer asset schedule',
    ['corporation.investments.rows'],
  ),
  field(
    'corporation',
    'DEDUCCIONES_PERSONA_MORAL',
    corporateDeductions,
    'totalAuthorizedDeductions',
    'Total de deducciones autorizadas incluido ajuste por inflación',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-44',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 2(f); Article 44',
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'totalAccumulatedIncome',
    'Total de ingresos acumulables',
    'money',
    'implemented',
    corporateRefs,
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(a)',
    ['corporation.accruedIncome', 'corporation.refundsDiscounts'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'totalAuthorizedDeductions',
    'Total de deducciones autorizadas',
    'money',
    'implemented',
    corporateRefs,
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(b)',
    ['corporation.authorizedDeductions'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'utilityBeforePtu',
    'Utilidad Fiscal o Pérdida Fiscal antes de PTU',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(d); Article 9(I)',
    [
      'corporation.accruedIncome',
      'corporation.refundsDiscounts',
      'corporation.authorizedDeductions',
    ],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'ptuPaid',
    'PTU pagada en el ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(e); Article 9(I)',
    ['corporation.ptuPaid'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'fiscalUtility',
    'Utilidad fiscal del ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(f); Article 9(I)',
    ['corporation.ptuPaid'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'priorLossesApplied',
    'Pérdidas fiscales de ejercicios anteriores',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(g); prior-loss amount is reviewed but history is unresolved',
    ['corporation.priorLossesApplied'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'fiscalResult',
    'Resultado fiscal',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(h); Article 9(II)',
    ['corporation.ptuPaid', 'corporation.priorLossesApplied'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'isrCaused',
    'Impuesto causado del ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(i); Article 9 rate',
    ['corporation.priorLossesApplied'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'isrExercise',
    'Impuesto sobre la Renta del Ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(k)',
    [
      'corporation.otherFacilidadesAndStimuli',
      'corporation.dividendTaxCredit',
      'corporation.foreignTaxCredit',
    ],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'otherFacilidadesAndStimuli',
    'Otras facilidades y estímulos por aplicar',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(c); ordinary slice requires explicit zero',
    ['corporation.otherFacilidadesAndStimuli'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'stimuliAppliedToTax',
    'Estímulos por aplicar al impuesto causado',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(j); ordinary slice requires explicit zero',
    ['corporation.otherFacilidadesAndStimuli'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'dividendTaxCredit',
    'Impuesto acreditable por dividendos o utilidades distribuidas',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(l); ordinary slice requires explicit zero',
    ['corporation.dividendTaxCredit'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'foreignTaxCredit',
    'Impuesto acreditable pagado en el extranjero',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(m); ordinary slice requires explicit zero',
    ['corporation.foreignTaxCredit'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'taxDue',
    'ISR a cargo del ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(p): ISR a cargo o a favor',
    ['corporation.provisionalPayments'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'balanceFavor',
    'ISR a favor del ejercicio',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-9',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(p): ISR a cargo o a favor',
    ['corporation.provisionalPayments'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'lowerUtilityCoefficientAuthorization',
    'Autorización de coeficiente de utilidad menor',
    'boolean',
    'unsupported',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-14',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(q); monthly provisional-payment reconstruction is outside the candidate',
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'provisionalPayments',
    'Pagos provisionales efectuados',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-14',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(n); Article 14',
    ['corporation.provisionalPayments'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'isrWithheld',
    'ISR retenido al contribuyente',
    'money',
    'implemented',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(o)',
    ['corporation.isrWithheld'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'subsidyForEmployment',
    'Subsidio para el empleo',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, payment application: subsidy for employment',
    ['corporation.subsidyForEmployment'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'compensations',
    'Compensaciones',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, payment application: compensations',
    ['corporation.compensations'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'otherPaymentApplications',
    'Otras aplicaciones',
    'money',
    'explicit-zero',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, payment application: other applications',
    ['corporation.otherPaymentApplications'],
  ),
  field(
    'corporation',
    'DECLARACION_ANUAL_MORAL',
    corporateDetermination,
    'credits',
    'Total de aplicaciones / acreditamientos',
    'money',
    'implemented',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-14',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, sections 3(n)-(p) and 4(e)',
    ['corporation.provisionalPayments', 'corporation.isrWithheld'],
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'coefficientOfUtility',
    'Coeficiente de utilidad del ejercicio',
    'money',
    'review-required',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-14',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(a); monthly provisional reconstruction is outside the candidate',
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'ptuObligation',
    'Obligado a calcular y pagar PTU',
    'boolean',
    'review-required',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(b); PTU obligation detail is not inferred',
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'cuca',
    'Cuenta de Capital de Aportación (CUCA)',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(c); movement schedule is outside the candidate',
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'cufin',
    'Cuenta de Utilidad Fiscal Neta (CUFIN)',
    'money',
    'unsupported',
    [
      'sat-mx-2025-guia-personas-morales-regimen-general',
      'sat-mx-lisr-articulo-77',
    ],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(d); Article 77 account schedule is outside the candidate',
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'reportableScheme',
    'Esquema reportable',
    'boolean',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(e); reportable-scheme declaration is outside the candidate',
  ),
  field(
    'corporation',
    'DATOS_ADICIONALES_MORAL',
    'SAT annual persons-morales Régimen General / Datos adicionales',
    'renewableEnergyGeneration',
    'Generación de energía de fuentes renovables o cogeneración eficiente',
    'boolean',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 5(f); special activity declaration is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'taxDue',
    'Cantidad a cargo',
    'money',
    'implemented',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(f)-(g)',
    ['corporation.provisionalPayments'],
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'balanceFavor',
    'ISR a favor del ejercicio',
    'money',
    'implemented',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 3(p)',
    ['corporation.provisionalPayments'],
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'employmentSubsidy',
    'Subsidio para el empleo',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(b); payment application is outside the corporate candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'compensations',
    'Compensaciones',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(c); payment application is outside the corporate candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'stimuliAppliedToPayment',
    'Estímulos al impuesto a cargo',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(d); payment application is outside the corporate candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'totalApplications',
    'Total de aplicaciones',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(e); electronic payment schedule is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'amountDue',
    'Cantidad a cargo',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(f)-(g); payment settlement is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'paymentWithin48Hours',
    'Pago realizado en las últimas 48 horas',
    'boolean',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(h); payment evidence is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'paymentDate',
    'Fecha del pago realizado en las últimas 48 horas',
    'text',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(i); payment evidence is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'paymentAmount48Hours',
    'Importe pagado en las últimas 48 horas',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(j); payment evidence is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'priorPaymentAmount',
    'Monto pagado con anterioridad',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(k); payment settlement is outside the candidate',
  ),
  field(
    'corporation',
    'PAGO',
    'SAT annual persons-morales Régimen General / Pago',
    'surcharges',
    'Recargos por la diferencia entre los pagos provisionales realizados',
    'money',
    'unsupported',
    ['sat-mx-2025-guia-personas-morales-regimen-general'],
    'GuiaLlenado_PersonasMoralesRegimenGeneral2025.pdf, section 4(m); payment settlement is outside the candidate',
  ),
] as const);

export const MEXICO_2025_RETURN_FIELD_CATALOG = MEXICO_2025_FIELD_APPLICABILITY;
export const MX_2025_FIELD_APPLICABILITY = MEXICO_2025_FIELD_APPLICABILITY;
export const MX_2025_RETURN_FIELD_CATALOG = MEXICO_2025_RETURN_FIELD_CATALOG;

export const MEXICO_2025_FORM_APPLICABILITY = deepFreeze([
  {
    taxpayerType: 'individual' as const,
    formId: 'SUELDOS',
    satSection: salaryIncome,
    status: 'partially-implemented' as const,
    sourceReferenceIds: salaryRefs,
  },
  {
    taxpayerType: 'individual' as const,
    formId: 'DECLARACION_ANUAL',
    satSection: salaryAnnual,
    status: 'partially-implemented' as const,
    sourceReferenceIds: salaryRefs,
  },
  {
    taxpayerType: 'individual' as const,
    formId: 'PAGO',
    satSection: 'SAT annual persons-físicas / Pago',
    status: 'partially-implemented' as const,
    sourceReferenceIds: salaryRefs,
  },
  {
    taxpayerType: 'sole-proprietor' as const,
    formId: 'ACTIVIDAD_PROFESIONAL',
    satSection: professionalIncome,
    status: 'partially-implemented' as const,
    sourceReferenceIds: professionalRefs,
  },
  {
    taxpayerType: 'sole-proprietor' as const,
    formId: 'DECLARACION_ANUAL_PROFESIONAL',
    satSection: professionalIncome,
    status: 'partially-implemented' as const,
    sourceReferenceIds: professionalRefs,
  },
  {
    taxpayerType: 'sole-proprietor' as const,
    formId: 'PAGO',
    satSection: 'SAT annual persons-físicas / Pago',
    status: 'partially-implemented' as const,
    sourceReferenceIds: professionalRefs,
  },
  {
    taxpayerType: 'corporation' as const,
    formId: 'INGRESOS_PERSONA_MORAL',
    satSection: corporateIncome,
    status: 'partially-implemented' as const,
    sourceReferenceIds: corporateRefs,
  },
  {
    taxpayerType: 'corporation' as const,
    formId: 'DEDUCCIONES_PERSONA_MORAL',
    satSection: corporateDeductions,
    status: 'partially-implemented' as const,
    sourceReferenceIds: corporateRefs,
  },
  {
    taxpayerType: 'corporation' as const,
    formId: 'DECLARACION_ANUAL_MORAL',
    satSection: corporateDetermination,
    status: 'partially-implemented' as const,
    sourceReferenceIds: corporateRefs,
  },
  {
    taxpayerType: 'corporation' as const,
    formId: 'DATOS_ADICIONALES_MORAL',
    satSection:
      'SAT annual persons-morales Régimen General / Datos adicionales',
    status: 'review-required' as const,
    sourceReferenceIds: corporateRefs,
  },
  {
    taxpayerType: 'corporation' as const,
    formId: 'PAGO',
    satSection: 'SAT annual payment',
    status: 'partially-implemented' as const,
    sourceReferenceIds: corporateRefs,
  },
] as const);
export const MX_2025_FORM_APPLICABILITY = MEXICO_2025_FORM_APPLICABILITY;
