export {
  createProviderWriteReconciliationService,
  ProposalService,
  ProposalPreparationBindingSchema,
  hashActionProposalApproval,
  type AbandonPreparedProposalInput,
  type AbandonPreparedProposalResult,
  type ApprovalHashInput,
  type AuthenticatedVisualDecisionContext,
  type ProposalActivityEvent,
  type ProposalAbandonmentReason,
  type ProposalErrorCode,
  type ProposalExpectedRevision,
  type ProposalIdempotencyLookup,
  type ProposalOperationScopeAssertion,
  type ProposalPreparationBinding,
  type ProviderWriteReconciliationService,
  type ProposalRepository,
  type ProposalRepositoryTransaction,
  type ProposalRepositoryWriteResult,
  type StoredDecision,
  type StoredProposalPreparation,
  type StoredProviderWriteAttempt,
  type StoredProviderWriteCompletion,
  type TrustedDisclosureGrantResolver,
  type TrustedProposalMaterializer,
} from '../shared/proposals.js';
