import type {
  SouthKorea2025CorporationInput,
  SouthKorea2025SoleProprietorInput,
} from './business.js';
import {
  SOUTH_KOREA_2025_CORPORATION_SCOPE,
  SOUTH_KOREA_2025_SOLE_PROPRIETOR_SCOPE,
} from './business.js';

export type SouthKorea2025BusinessFixture = {
  readonly id: string;
  readonly description: string;
  readonly input: SouthKorea2025SoleProprietorInput;
  readonly expectedValues: Readonly<Record<string, string>>;
};

export type SouthKorea2025CorporationFixture = {
  readonly id: string;
  readonly description: string;
  readonly input: SouthKorea2025CorporationInput;
  readonly expectedValues: Readonly<Record<string, string>>;
};

const soleInput = (
  overrides: Partial<
    Omit<SouthKorea2025SoleProprietorInput, 'schemaVersion' | 'scope'>
  >,
): SouthKorea2025SoleProprietorInput => ({
  schemaVersion: 1,
  scope: { ...SOUTH_KOREA_2025_SOLE_PROPRIETOR_SCOPE },
  domesticResident: true,
  hasCrossBorderActivity: false,
  onlyOrdinaryBusinessIncome: true,
  hasEmploymentIncome: false,
  hasInvestmentIncome: false,
  hasPensionIncome: false,
  hasOtherGlobalIncome: false,
  hasDailyEmploymentIncome: false,
  hasForeignSourceIncome: false,
  hasRetirementIncome: false,
  usesSimplifiedExpenseRate: false,
  hasBusinessLoss: false,
  isCompliantFilingBusiness: false,
  hasTaxReductionOrExemption: false,
  annualGrossBusinessRevenue: '0',
  returnsAndAllowances: '0',
  necessaryBusinessExpenses: '0',
  basicDeductionCount: '1',
  nationalPensionContribution: '0',
  otherIncomeDeductions: '0',
  otherTaxCredits: '0',
  incomeTaxReduction: '0',
  prepaidIncomeTax: '0',
  ...overrides,
});

const corporationInput = (
  overrides: Partial<
    Omit<SouthKorea2025CorporationInput, 'schemaVersion' | 'scope'>
  >,
): SouthKorea2025CorporationInput => ({
  schemaVersion: 1,
  scope: { ...SOUTH_KOREA_2025_CORPORATION_SCOPE },
  domesticCorporation: true,
  hasCrossBorderActivity: false,
  standaloneCorporation: true,
  consolidatedGroup: false,
  hasBranchOutsideKorea: false,
  hasTaxAdjustments: false,
  hasCarriedForwardLosses: false,
  hasNonTaxableIncome: false,
  hasIncomeDeductions: false,
  hasTaxCredits: false,
  hasTaxReductionOrExemption: false,
  hasPenaltiesOrAdditionalTax: false,
  hasCapitalGains: false,
  hasInvestmentIncome: false,
  hasRealEstateIncome: false,
  hasForeignSourceIncome: false,
  annualGrossRevenue: '0',
  returnsAndAllowances: '0',
  deductibleBusinessExpenses: '0',
  prepaidCorporateTax: '0',
  ...overrides,
});

/** Manually authored outputs; these values are not generated by the calculator. */
export const SOUTH_KOREA_2025_SOLE_PROPRIETOR_FIXTURES: readonly SouthKorea2025BusinessFixture[] =
  [
    {
      id: 'sole-proprietor-ledger-50m',
      description:
        'KRW 50,000,000 gross receipts, KRW 2,000,000 returns and KRW 15,000,000 reviewed ledger expenses.',
      input: soleInput({
        annualGrossBusinessRevenue: '50000000',
        returnsAndAllowances: '2000000',
        necessaryBusinessExpenses: '15000000',
        prepaidIncomeTax: '1000000',
      }),
      expectedValues: {
        'business.grossRevenue': '50000000',
        'business.returnsAndAllowances': '2000000',
        'business.netRevenue': '48000000',
        'business.necessaryBusinessExpenses': '15000000',
        'business.netIncome': '33000000',
        'business.globalIncome': '33000000',
        'deduction.basicPersonal': '1500000',
        'deduction.nationalPension': '0',
        'deduction.otherIncomeDeductions': '0',
        'business.taxBase': '31500000',
        'business.calculatedTax': '3465000',
        'credit.standardTaxCredit': '70000',
        'credit.otherTaxCredits': '0',
        'credit.incomeTaxReduction': '0',
        'tax.taxAfterReduction': '3465000',
        'credit.totalTaxCredits': '70000',
        'business.determinedTax': '3395000',
        'business.prepaidIncomeTax': '1000000',
        'business.balanceDueOrRefund': '2395000',
        'business.localIncomeTax': '339500',
      },
    },
    {
      id: 'sole-proprietor-upper-income-band',
      description:
        'KRW 250,000,000 gross receipts with KRW 20,000,000 reviewed ledger expenses, exercising the 38% national band.',
      input: soleInput({
        annualGrossBusinessRevenue: '250000000',
        necessaryBusinessExpenses: '20000000',
      }),
      expectedValues: {
        'business.grossRevenue': '250000000',
        'business.returnsAndAllowances': '0',
        'business.netRevenue': '250000000',
        'business.necessaryBusinessExpenses': '20000000',
        'business.netIncome': '230000000',
        'business.globalIncome': '230000000',
        'deduction.basicPersonal': '1500000',
        'deduction.nationalPension': '0',
        'deduction.otherIncomeDeductions': '0',
        'business.taxBase': '228500000',
        'business.calculatedTax': '66890000',
        'credit.standardTaxCredit': '70000',
        'credit.otherTaxCredits': '0',
        'credit.incomeTaxReduction': '0',
        'tax.taxAfterReduction': '66890000',
        'credit.totalTaxCredits': '70000',
        'business.determinedTax': '66820000',
        'business.prepaidIncomeTax': '0',
        'business.balanceDueOrRefund': '66820000',
        'business.localIncomeTax': '6682000',
      },
    },
    {
      id: 'sole-proprietor-fractional-intermediates',
      description:
        'Sub-won revenue and expense inputs prove exact rational intermediates are retained until report truncation.',
      input: soleInput({
        annualGrossBusinessRevenue: '5000000.01',
        necessaryBusinessExpenses: '1500000.005',
      }),
      expectedValues: {
        'business.grossRevenue': '5000000',
        'business.returnsAndAllowances': '0',
        'business.netRevenue': '5000000',
        'business.necessaryBusinessExpenses': '1500000',
        'business.netIncome': '3500000',
        'business.globalIncome': '3500000',
        'deduction.basicPersonal': '1500000',
        'deduction.nationalPension': '0',
        'deduction.otherIncomeDeductions': '0',
        'business.taxBase': '2000000',
        'business.calculatedTax': '120000',
        'credit.standardTaxCredit': '70000',
        'credit.otherTaxCredits': '0',
        'credit.incomeTaxReduction': '0',
        'tax.taxAfterReduction': '120000',
        'credit.totalTaxCredits': '70000',
        'business.determinedTax': '50000',
        'business.prepaidIncomeTax': '0',
        'business.balanceDueOrRefund': '50000',
        'business.localIncomeTax': '5000',
      },
    },
  ];

/** Manually authored outputs; these values are not generated by the calculator. */
export const SOUTH_KOREA_2025_CORPORATION_FIXTURES: readonly SouthKorea2025CorporationFixture[] =
  [
    {
      id: 'corporation-ordinary-190m',
      description:
        'KRW 300,000,000 ordinary revenue less KRW 10,000,000 returns and KRW 100,000,000 reviewed expenses.',
      input: corporationInput({
        annualGrossRevenue: '300000000',
        returnsAndAllowances: '10000000',
        deductibleBusinessExpenses: '100000000',
        prepaidCorporateTax: '5000000',
      }),
      expectedValues: {
        'corporate.grossRevenue': '300000000',
        'corporate.returnsAndAllowances': '10000000',
        'corporate.netRevenue': '290000000',
        'corporate.deductibleBusinessExpenses': '100000000',
        'corporate.accountingProfit': '190000000',
        'corporate.taxBase': '190000000',
        'corporate.calculatedTax': '17100000',
        'corporate.taxCredits': '0',
        'corporate.taxReduction': '0',
        'corporate.taxAfterReduction': '17100000',
        'corporate.prepaidCorporateTax': '5000000',
        'corporate.balanceDueOrRefund': '12100000',
        'corporate.localIncomeTax': '1710000',
      },
    },
    {
      id: 'corporation-21-percent-band',
      description:
        'KRW 25,000,000,000 corporate tax base exercising the published 21% band.',
      input: corporationInput({ annualGrossRevenue: '25000000000' }),
      expectedValues: {
        'corporate.grossRevenue': '25000000000',
        'corporate.returnsAndAllowances': '0',
        'corporate.netRevenue': '25000000000',
        'corporate.deductibleBusinessExpenses': '0',
        'corporate.accountingProfit': '25000000000',
        'corporate.taxBase': '25000000000',
        'corporate.calculatedTax': '4830000000',
        'corporate.taxCredits': '0',
        'corporate.taxReduction': '0',
        'corporate.taxAfterReduction': '4830000000',
        'corporate.prepaidCorporateTax': '0',
        'corporate.balanceDueOrRefund': '4830000000',
        'corporate.localIncomeTax': '483000000',
      },
    },
    {
      id: 'corporation-fractional-threshold',
      description:
        'A sub-won amount immediately above the KRW 200,000,000 corporate rate boundary.',
      input: corporationInput({ annualGrossRevenue: '200000000.01' }),
      expectedValues: {
        'corporate.grossRevenue': '200000000',
        'corporate.returnsAndAllowances': '0',
        'corporate.netRevenue': '200000000',
        'corporate.deductibleBusinessExpenses': '0',
        'corporate.accountingProfit': '200000000',
        'corporate.taxBase': '200000000',
        'corporate.calculatedTax': '18000000',
        'corporate.taxCredits': '0',
        'corporate.taxReduction': '0',
        'corporate.taxAfterReduction': '18000000',
        'corporate.prepaidCorporateTax': '0',
        'corporate.balanceDueOrRefund': '18000000',
        'corporate.localIncomeTax': '1800000',
      },
    },
  ];
