import { describe, expect, it } from 'vitest';

import {
  guardOfflineSyncOperation,
  mergeBudgetConflict,
  mergeSchedulerConflict,
  reduceAppendOnlyEvent,
  reduceFinanceTransaction,
  reduceShoppingQuantity,
} from './conflicts.js';

const ids = {
  client: '018f1f5e-6f47-7d61-a6dd-1e86f8b8f001',
  operationA: '018f1f5e-6f47-7d61-a6dd-1e86f8b8f002',
  operationB: '018f1f5e-6f47-7d61-a6dd-1e86f8b8f003',
  operationC: '018f1f5e-6f47-7d61-a6dd-1e86f8b8f004',
} as const;

const makeSyncOperation = (entityType: string, payload: unknown = {}) => ({
  schemaVersion: 1 as const,
  clientId: ids.client,
  operationId: ids.operationA,
  entity: { type: entityType, id: 'local-record-1' },
  mutation: { kind: 'update' as const, payload },
  baseRevision: 1,
  dependencies: [],
  actorIntent: 'Edit this record while offline.',
  createdAt: '2026-08-09T16:00:00.000Z',
});

describe('offline operation boundary', () => {
  it('accepts only local domain entities and never emits provider writes', () => {
    const input = makeSyncOperation('scheduler.item', {
      title: 'Discuss a Google Calendar write as ordinary text',
    });
    const result = guardOfflineSyncOperation(input);

    expect(result).toMatchObject({ status: 'accepted', providerWrites: [] });
    expect(Object.isFrozen(result)).toBe(true);
    expect(Object.isFrozen(input)).toBe(false);
  });

  it('rejects encoded Google Calendar operations with a safe error', () => {
    const result = guardOfflineSyncOperation(
      makeSyncOperation('google-calendar.event', {
        action: 'create',
        calendarId: 'primary',
      }),
    );

    expect(result).toEqual({
      status: 'rejected',
      safeError: {
        code: 'offline-provider-write-forbidden',
        message: 'Offline operations may only mutate EMDO local records.',
        retryable: false,
      },
      providerWrites: [],
    });
  });

  it('rejects client-authored audit events because audit is server-owned', () => {
    const result = guardOfflineSyncOperation(
      makeSyncOperation('audit.event', {
        eventType: 'proposal.approved',
      }),
    );

    expect(result).toEqual({
      status: 'rejected',
      safeError: {
        code: 'offline-audit-write-forbidden',
        message: 'Audit records are generated by the server.',
        retryable: false,
      },
      providerWrites: [],
    });
  });

  it('fails closed without reflecting malformed input in the safe error', () => {
    const result = guardOfflineSyncOperation({
      entity: { type: 'scheduler.item' },
      secret: 'do-not-reflect-me',
    });

    expect(result).toEqual({
      status: 'rejected',
      safeError: {
        code: 'offline-operation-invalid',
        message: 'The offline operation is invalid.',
        retryable: false,
      },
      providerWrites: [],
    });
    expect(JSON.stringify(result)).not.toContain('do-not-reflect-me');
  });

  it.each(['cyclic', 'too-deep'] as const)(
    'safely rejects %s JSON before recursive schema parsing',
    (kind) => {
      let payload: Record<string, unknown> = {};
      if (kind === 'cyclic') {
        payload.self = payload;
      } else {
        for (let depth = 0; depth < 80; depth += 1) {
          payload = { nested: payload };
        }
      }

      expect(
        guardOfflineSyncOperation(makeSyncOperation('scheduler.item', payload)),
      ).toMatchObject({
        status: 'rejected',
        safeError: { code: 'offline-operation-invalid' },
      });
    },
  );
});

describe('append-only conversation and audit conflicts', () => {
  const emptyState = { events: [] } as const;
  const append = {
    operationId: ids.operationA,
    eventId: 'event-1',
    kind: 'append' as const,
    payload: { message: 'Hello' },
  };

  it.each(['conversation', 'audit'] as const)(
    'only appends immutable %s events',
    (recordKind) => {
      const applied = reduceAppendOnlyEvent({
        recordKind,
        state: emptyState,
        operation: append,
      });

      expect(applied).toMatchObject({
        status: 'applied',
        state: { events: [append] },
        providerWrites: [],
      });
      expect(Object.isFrozen(applied.state.events[0]?.payload)).toBe(true);

      const rejected = reduceAppendOnlyEvent({
        recordKind,
        state: applied.state,
        operation: {
          operationId: ids.operationB,
          eventId: 'event-1',
          kind: 'delete',
          payload: null,
        },
      });

      expect(rejected).toMatchObject({
        status: 'rejected',
        state: applied.state,
        safeError: { code: 'append-only-mutation-forbidden' },
        providerWrites: [],
      });
    },
  );

  it('deduplicates an operation and surfaces a reused event ID for review', () => {
    const applied = reduceAppendOnlyEvent({
      recordKind: 'conversation',
      state: emptyState,
      operation: append,
    });

    expect(
      reduceAppendOnlyEvent({
        recordKind: 'conversation',
        state: applied.state,
        operation: append,
      }).status,
    ).toBe('duplicate');

    expect(
      reduceAppendOnlyEvent({
        recordKind: 'conversation',
        state: applied.state,
        operation: {
          ...append,
          operationId: ids.operationB,
          payload: { message: 'Replacement' },
        },
      }),
    ).toMatchObject({
      status: 'needs-review',
      conflicts: [{ field: 'eventId', material: true }],
    });
  });

  it('converges on canonical event order regardless of arrival order', () => {
    const eventA = append;
    const eventB = {
      operationId: ids.operationB,
      eventId: 'event-2',
      kind: 'append' as const,
      payload: { message: 'World' },
    };
    const apply = (
      first: {
        operationId: string;
        eventId: string;
        kind: 'append';
        payload: { message: string };
      },
      second: {
        operationId: string;
        eventId: string;
        kind: 'append';
        payload: { message: string };
      },
    ) =>
      reduceAppendOnlyEvent({
        recordKind: 'conversation',
        state: reduceAppendOnlyEvent({
          recordKind: 'conversation',
          state: emptyState,
          operation: first,
        }).state,
        operation: second,
      }).state;

    expect(apply(eventA, eventB)).toEqual(apply(eventB, eventA));
  });
});

describe('finance conflicts', () => {
  const transaction = {
    id: 'transaction-1',
    currency: 'CAD' as const,
    originalAmountCadMinor: 1_000,
    adjustments: [],
    reversal: null,
    appliedOperationIds: [],
  } as const;

  it('preserves the original amount and applies integer-CAD adjustments', () => {
    const adjusted = reduceFinanceTransaction({
      state: transaction,
      operation: {
        operationId: ids.operationA,
        kind: 'adjustment',
        amountCadMinor: 125,
        reason: 'Correct the imported statement amount.',
      },
    });

    expect(adjusted).toMatchObject({
      status: 'applied',
      state: {
        originalAmountCadMinor: 1_000,
        effectiveAmountCadMinor: 1_125,
        adjustments: [{ amountCadMinor: 125 }],
      },
      providerWrites: [],
    });
    expect(
      reduceFinanceTransaction({
        state: adjusted.state,
        operation: {
          operationId: ids.operationA,
          kind: 'adjustment',
          amountCadMinor: 125,
          reason: 'Correct the imported statement amount.',
        },
      }).status,
    ).toBe('duplicate');

    expect(
      reduceFinanceTransaction({
        state: adjusted.state,
        operation: {
          operationId: ids.operationA,
          kind: 'adjustment',
          amountCadMinor: 500,
          reason: 'Attempt to reuse the operation ID.',
        },
      }),
    ).toMatchObject({
      status: 'needs-review',
      safeError: { code: 'finance-idempotency-conflict' },
    });
  });

  it('uses a reversal instead of deleting the transaction', () => {
    const reversed = reduceFinanceTransaction({
      state: transaction,
      operation: {
        operationId: ids.operationB,
        kind: 'reversal',
        reason: 'Reverse a duplicate statement line.',
      },
    });

    expect(reversed).toMatchObject({
      status: 'applied',
      state: {
        originalAmountCadMinor: 1_000,
        effectiveAmountCadMinor: 0,
        reversal: { operationId: ids.operationB },
      },
    });
  });

  it.each(['replace', 'delete'] as const)(
    'requires review rather than applying a direct %s',
    (kind) => {
      const result = reduceFinanceTransaction({
        state: transaction,
        operation: {
          operationId: ids.operationC,
          kind,
          replacementAmountCadMinor: kind === 'replace' ? 999 : undefined,
        },
      });

      expect(result).toMatchObject({
        status: 'needs-review',
        state: transaction,
        safeError: { code: 'finance-mutation-requires-ledger-entry' },
        providerWrites: [],
      });
    },
  );

  it('makes a reversal dominate adjustments regardless of arrival order', () => {
    const adjustment = {
      operationId: ids.operationB,
      kind: 'adjustment' as const,
      amountCadMinor: 1,
      reason: 'Late correction after reversal.',
    };
    const reversal = {
      operationId: ids.operationA,
      kind: 'reversal' as const,
      reason: 'Reverse a duplicate statement line.',
    };
    const reversalFirst = reduceFinanceTransaction({
      state: transaction,
      operation: reversal,
    });
    const reversalThenAdjustment = reduceFinanceTransaction({
      state: reversalFirst.state,
      operation: adjustment,
    });
    const adjustmentFirst = reduceFinanceTransaction({
      state: transaction,
      operation: adjustment,
    });
    const adjustmentThenReversal = reduceFinanceTransaction({
      state: adjustmentFirst.state,
      operation: reversal,
    });

    expect(reversalThenAdjustment).toMatchObject({
      status: 'ignored',
      safeError: { code: 'finance-reversal-dominates' },
    });
    expect(reversalThenAdjustment.state).toEqual(adjustmentThenReversal.state);
  });

  it('returns a safe review result when an adjustment would overflow', () => {
    const result = reduceFinanceTransaction({
      state: {
        ...transaction,
        originalAmountCadMinor: Number.MAX_SAFE_INTEGER,
      },
      operation: {
        operationId: ids.operationC,
        kind: 'adjustment',
        amountCadMinor: 1,
        reason: 'This amount exceeds the supported ledger range.',
      },
    });

    expect(result).toMatchObject({
      status: 'needs-review',
      state: { amountConflict: true },
      safeError: { code: 'finance-amount-overflow' },
    });
  });

  it('converges when an initially unsafe adjustment is later compensated', () => {
    const atLimit = {
      ...transaction,
      originalAmountCadMinor: Number.MAX_SAFE_INTEGER,
    };
    const compensating = {
      operationId: ids.operationA,
      kind: 'adjustment' as const,
      amountCadMinor: -2,
      reason: 'Create room inside the safe integer range.',
    };
    const initiallyUnsafe = {
      operationId: ids.operationB,
      kind: 'adjustment' as const,
      amountCadMinor: 2,
      reason: 'Requires the compensating adjustment.',
    };
    type Adjustment = {
      operationId: string;
      kind: 'adjustment';
      amountCadMinor: number;
      reason: string;
    };
    const apply = (first: Adjustment, second: Adjustment) =>
      reduceFinanceTransaction({
        state: reduceFinanceTransaction({
          state: atLimit,
          operation: first,
        }).state,
        operation: second,
      }).state;

    expect(apply(compensating, initiallyUnsafe)).toEqual(
      apply(initiallyUnsafe, compensating),
    );
    expect(apply(compensating, initiallyUnsafe)).toMatchObject({
      effectiveAmountCadMinor: Number.MAX_SAFE_INTEGER,
      amountConflict: false,
    });
  });

  it('rejects a ledger with any unsafe intermediate amount', () => {
    const result = reduceFinanceTransaction({
      state: {
        ...transaction,
        originalAmountCadMinor: Number.MAX_SAFE_INTEGER,
        adjustments: [
          {
            operationId: ids.operationA,
            amountCadMinor: 2,
            reason: 'First adjustment crosses the safe integer boundary.',
          },
          {
            operationId: ids.operationB,
            amountCadMinor: -2,
            reason: 'Second adjustment appears to restore the amount.',
          },
        ],
        appliedOperationIds: [ids.operationA, ids.operationB],
      },
      operation: {
        operationId: ids.operationC,
        kind: 'delete',
      },
    });

    expect(result).toMatchObject({
      status: 'rejected',
      state: null,
      safeError: { code: 'offline-conflict-input-invalid' },
    });
  });

  it('merges independent budget categories and reviews divergent edits', () => {
    const base = {
      id: 'budget-2026-08',
      currency: 'CAD' as const,
      allocationsCadMinor: { groceries: 40_000, transit: 10_000 },
    };
    const independent = mergeBudgetConflict({
      base,
      local: {
        ...base,
        allocationsCadMinor: { groceries: 45_000, transit: 10_000 },
      },
      remote: {
        ...base,
        allocationsCadMinor: { groceries: 40_000, transit: 12_000 },
      },
    });

    expect(independent).toMatchObject({
      status: 'applied',
      state: { allocationsCadMinor: { groceries: 45_000, transit: 12_000 } },
    });

    const divergent = mergeBudgetConflict({
      base,
      local: {
        ...base,
        allocationsCadMinor: { groceries: 45_000, transit: 10_000 },
      },
      remote: {
        ...base,
        allocationsCadMinor: { groceries: 43_000, transit: 12_000 },
      },
    });

    expect(divergent).toMatchObject({
      status: 'needs-review',
      state: { allocationsCadMinor: { groceries: 40_000, transit: 12_000 } },
      conflicts: [
        {
          field: 'allocationsCadMinor.groceries',
          base: 40_000,
          local: 45_000,
          remote: 43_000,
          material: true,
        },
      ],
      providerWrites: [],
    });
  });
});

describe('shopping quantity conflicts', () => {
  const state = {
    itemId: 'shopping-item-1',
    quantityMinorUnits: 2_000,
    tombstoned: false,
    appliedOperationIds: [],
  } as const;

  it('applies each quantity delta exactly once', () => {
    const operation = {
      operationId: ids.operationA,
      kind: 'delta' as const,
      quantityMinorUnits: 500,
    };
    const applied = reduceShoppingQuantity({ state, operation });

    expect(applied).toMatchObject({
      status: 'applied',
      state: { quantityMinorUnits: 2_500 },
      providerWrites: [],
    });
    expect(
      reduceShoppingQuantity({ state: applied.state, operation }),
    ).toMatchObject({ status: 'duplicate', state: applied.state });

    expect(
      reduceShoppingQuantity({
        state: applied.state,
        operation: { ...operation, quantityMinorUnits: 1_000 },
      }),
    ).toMatchObject({
      status: 'needs-review',
      safeError: { code: 'shopping-idempotency-conflict' },
    });
  });

  it('makes tombstones dominate deltas in either arrival order', () => {
    const delta = {
      operationId: ids.operationA,
      kind: 'delta' as const,
      quantityMinorUnits: 500,
    };
    const tombstone = {
      operationId: ids.operationB,
      kind: 'tombstone' as const,
    };

    const deltaThenTombstone = reduceShoppingQuantity({
      state: reduceShoppingQuantity({ state, operation: delta }).state,
      operation: tombstone,
    });
    const tombstoneThenDelta = reduceShoppingQuantity({
      state: reduceShoppingQuantity({ state, operation: tombstone }).state,
      operation: delta,
    });

    expect(deltaThenTombstone.state).toEqual(tombstoneThenDelta.state);
    expect(tombstoneThenDelta).toMatchObject({
      status: 'ignored',
      state: { quantityMinorUnits: 0, tombstoned: true },
      safeError: { code: 'shopping-item-tombstoned' },
    });
  });

  it('surfaces a negative quantity for review without changing visible quantity', () => {
    const result = reduceShoppingQuantity({
      state,
      operation: {
        operationId: ids.operationC,
        kind: 'delta',
        quantityMinorUnits: -2_001,
      },
    });

    expect(result).toMatchObject({
      status: 'needs-review',
      state: {
        quantityMinorUnits: state.quantityMinorUnits,
        quantityConflict: true,
      },
      safeError: { code: 'shopping-negative-quantity-conflict' },
    });
  });

  it('converges when a negative delta is later compensated', () => {
    const quantityOne = { ...state, quantityMinorUnits: 1 };
    const negative = {
      operationId: ids.operationA,
      kind: 'delta' as const,
      quantityMinorUnits: -2,
    };
    const positive = {
      operationId: ids.operationB,
      kind: 'delta' as const,
      quantityMinorUnits: 2,
    };
    type Delta = {
      operationId: string;
      kind: 'delta';
      quantityMinorUnits: number;
    };
    const apply = (first: Delta, second: Delta) =>
      reduceShoppingQuantity({
        state: reduceShoppingQuantity({
          state: quantityOne,
          operation: first,
        }).state,
        operation: second,
      }).state;

    expect(apply(negative, positive)).toEqual(apply(positive, negative));
    expect(apply(negative, positive)).toMatchObject({
      quantityMinorUnits: 1,
      quantityConflict: false,
    });
  });
});

describe('scheduler conflicts', () => {
  const base = {
    id: 'scheduler-item-1',
    title: 'Dentist',
    notes: null,
    location: null,
    startsAt: '2026-08-11T14:00:00-04:00',
    endsAt: '2026-08-11T15:00:00-04:00',
    recurrence: null,
    attendees: ['member-a'],
    completion: 'open' as const,
  };

  it('merges changes to independent fields deterministically', () => {
    const result = mergeSchedulerConflict({
      base,
      local: { ...base, title: 'Dentist appointment' },
      remote: { ...base, location: 'Toronto Dental' },
    });

    expect(result).toMatchObject({
      status: 'applied',
      state: {
        title: 'Dentist appointment',
        location: 'Toronto Dental',
      },
      conflicts: [],
      providerWrites: [],
    });
  });

  it('treats start and end as one material time field', () => {
    const result = mergeSchedulerConflict({
      base,
      local: { ...base, startsAt: '2026-08-11T13:30:00-04:00' },
      remote: { ...base, endsAt: '2026-08-11T15:30:00-04:00' },
    });

    expect(result).toMatchObject({
      status: 'needs-review',
      conflicts: [{ field: 'time', material: true }],
    });
    expect(result.state.startsAt).toBe(base.startsAt);
    expect(result.state.endsAt).toBe(base.endsAt);
  });

  it.each([
    [
      'recurrence',
      { recurrence: 'FREQ=WEEKLY' },
      { recurrence: 'FREQ=MONTHLY' },
    ],
    [
      'attendees',
      { attendees: ['member-a', 'member-b'] },
      { attendees: ['member-a', 'member-c'] },
    ],
    ['completion', { completion: 'completed' }, { completion: 'skipped' }],
  ] as const)(
    'surfaces divergent %s changes for review',
    (field, localPatch, remotePatch) => {
      const result = mergeSchedulerConflict({
        base,
        local: { ...base, ...localPatch },
        remote: { ...base, ...remotePatch },
      });

      expect(result).toMatchObject({
        status: 'needs-review',
        conflicts: [{ field, material: true }],
      });
    },
  );

  it('canonicalizes attendee ordering instead of reporting a false conflict', () => {
    const result = mergeSchedulerConflict({
      base: { ...base, attendees: ['member-a', 'member-b'] },
      local: { ...base, attendees: ['member-b', 'member-a'] },
      remote: { ...base, attendees: ['member-a', 'member-b'] },
    });

    expect(result.status).toBe('applied');
    expect(result.state.attendees).toEqual(['member-a', 'member-b']);
  });
});

describe('conflict reducer validation boundary', () => {
  it.each([
    ['append-only', () => reduceAppendOnlyEvent({ secret: 'do-not-reflect' })],
    [
      'finance transaction',
      () => reduceFinanceTransaction({ secret: 'do-not-reflect' }),
    ],
    ['budget', () => mergeBudgetConflict({ secret: 'do-not-reflect' })],
    [
      'shopping quantity',
      () => reduceShoppingQuantity({ secret: 'do-not-reflect' }),
    ],
    ['scheduler', () => mergeSchedulerConflict({ secret: 'do-not-reflect' })],
  ] as const)(
    'returns a non-reflecting safe error for invalid %s input',
    (_, run) => {
      const result = run();

      expect(result).toEqual({
        status: 'rejected',
        state: null,
        conflicts: [],
        safeError: {
          code: 'offline-conflict-input-invalid',
          message: 'The conflict reducer input is invalid.',
          retryable: false,
        },
        providerWrites: [],
      });
      expect(JSON.stringify(result)).not.toContain('do-not-reflect');
    },
  );

  it('safely rejects a cyclic append payload', () => {
    const payload: Record<string, unknown> = {};
    payload.self = payload;

    expect(
      reduceAppendOnlyEvent({
        recordKind: 'conversation',
        state: { events: [] },
        operation: {
          operationId: ids.operationA,
          eventId: 'event-cyclic',
          kind: 'append',
          payload,
        },
      }),
    ).toMatchObject({
      status: 'rejected',
      state: null,
      safeError: { code: 'offline-conflict-input-invalid' },
    });
  });
});
