"""Rebuild derived public CRA XFA field inventory from immutable local PDF captures.
Run from repository root. This script performs no network requests or source updates.
"""
from pathlib import Path
import hashlib, json, re, xml.etree.ElementTree as ET
from pypdf import PdfReader
root = Path(__file__).resolve().parents[1]
forms = {'T2': 't2-fill-25e.pdf', 'S1': 't2sch1-fill-25e.pdf', 'S5': 't2sch5-fill-25e.pdf', 'S50': 't2sch50-fill-19e.pdf', 'S500': 't2sch500-fill-23e.pdf', 'GIFI100': 't2sch100-fill-20e.pdf', 'GIFI125': 't2sch125-fill-23e.pdf', 'GIFI141': 't2sch141-fill-23e.pdf'}
records = []
for form, file in forms.items():
    path = root / 'sources' / file
    reader = PdfReader(path)
    xfa = reader.trailer['/Root']['/AcroForm'].get_object()['/XFA']
    template = next(xfa[i+1].get_object().get_data() for i in range(0,len(xfa),2) if str(xfa[i]) == 'template')
    tree = ET.fromstring(template)
    ns = {'x': tree.tag.split('}')[0][1:]}
    def text(node): return ''.join(node.itertext()) if node is not None else None
    field_ordinal = [0]
    def visit(node, parents):
        label = node.attrib.get('name')
        current = parents + ([label] if label else [])
        if node.tag.endswith('}field'):
            field_ordinal[0] += 1
            scripts = [{ 'activity': event.attrib.get('activity'), 'script': text(event.find('x:script', ns)) } for event in node.findall('x:event', ns)]
            records.append({ 'ordinal': field_ordinal[0], 'form': form, 'sourceFile': file, 'sourceSha256': hashlib.sha256(path.read_bytes()).hexdigest(), 'path': '.'.join(current), 'name': label, 'assist': text(node.find('x:assist/x:speak', ns)), 'uiPicture': text(node.find('x:ui/x:picture', ns)), 'formatPicture': text(node.find('x:format/x:picture', ns)), 'maxChars': next((int(n.attrib['maxChars']) for n in node.iter() if 'maxChars' in n.attrib and int(n.attrib['maxChars']) > 0), None), 'combCells': next((int(n.attrib['numberOfCells']) for n in node.iter() if 'numberOfCells' in n.attrib), None), 'valueType': next((x.tag.split('}')[-1] for v in node.findall('x:value', ns) for x in v), None), 'scripts': [s for s in scripts if s['activity'] in ['change','calculate','validate','exit']], 'items': [text(x) for items in node.findall('x:items', ns) for x in items] })
        for child in node: visit(child,current)
    visit(tree, [])
(root / 'sources' / 'xfa-field-inventory.json').write_text(json.dumps(records, indent=2, ensure_ascii=False)+'\n')
print(f'{len(records)} fields from {len(forms)} official forms')

compact = []
for f in records:
    scripts = '\n'.join(s['script'] or '' for s in f['scripts'])
    numeric = re.search(r'validateKeystrokeNumeric\(this,\s*(\d+),\s*(true|false)', scripts)
    floating = re.search(r'validateKeystrokeFloat\(this,\s*(\d+),\s*(\d+),\s*(true|false)', scripts)
    currency = re.search(r'currencyKeystroke\((true|false),\s*(\d+)\)', scripts)
    digits = int(numeric[1]) if numeric else int(floating[1]) if floating else int(currency[2]) if currency else None
    places = 0 if numeric else int(floating[2]) if floating else 2 if currency else None
    positive = numeric[2] == 'true' if numeric else floating[3] == 'true' if floating else currency[1] == 'true' if currency else None
    compact.append({ 'ordinal': f['ordinal'], 'form': f['form'], 'sourceFile': f['sourceFile'], 'path': f['path'], 'assist': f['assist'], 'uiPicture': f['uiPicture'], 'formatPicture': f['formatPicture'], 'maxIntegerDigits': digits, 'decimalPlaces': places, 'positiveOnly': positive, 'maxChars': f['maxChars'], 'combCells': f['combCells'], 'validation': numeric.group(0)+');' if numeric else floating.group(0)+');' if floating else currency.group(0) if currency else None })
header = "import { deepFreeze } from '@emdo/contracts';\nexport type CorporateXfaField = { ordinal: number; form: string; sourceFile: string; path: string; assist: string | null; uiPicture: string | null; formatPicture: string | null; maxIntegerDigits: number | null; decimalPlaces: number | null; positiveOnly: boolean | null; validation: string | null; maxChars: number | null; combCells: number | null };\n/** Generated by scripts/capture-xfa.py from immutable official PDF template packets. */\nexport const CORPORATE_XFA_FIELDS = deepFreeze("
(root / 'xfa-inventory.ts').write_text(header + json.dumps(compact, ensure_ascii=False, separators=(',', ':')) + ' satisfies CorporateXfaField[]);\n')
