"""Reproduce single-filer IRS tax/EIC tables from the pinned 1040 instruction PDF.
No rates are used to synthesize tax-table rows. Known PDF layout splits are explicit.
"""
import hashlib
import json
from pathlib import Path
import re
import subprocess

root = Path(__file__).parent
manifest = json.loads((root / 'manifest.json').read_text())
source = next(item for item in manifest if item['id'] == 'irs-2025-i1040gi')
assert hashlib.sha256((root / source['file']).read_bytes()).hexdigest() == source['documentHash']
text = subprocess.check_output(['pdftotext', '-layout', str(root / source['file']), '-'], text=True)
def rows(section, width):
    result = {}
    for line in section.splitlines():
        prefix = re.match(r'^[\s\d,*]+', line)
        if not prefix: continue
        tokens = prefix.group().split()
        if len(tokens) % width: continue
        for i in range(0, len(tokens), width):
            parts = tokens[i:i+width]
            if '*' in parts[0] or '*' in parts[1]: continue
            lo, hi = (int(x.replace(',', '')) for x in parts[:2])
            if not 0 < hi-lo <= 50: continue
            if '*' in parts[2]: continue
            value = int(parts[2].replace(',', ''))
            if lo in result: assert result[lo] == [hi,value]
            result[lo] = [hi,value]
    return result
start = text.index('Sample Table', text.index('2025 Earned Income Credit (EIC) Table'))
end = text.index('2025 Tax Computation Worksheet', start)
tax = rows(text[start:end],6)
# Page68 first column wraps these two rows vertically; read directly from PDF.
tax[5] = [15,1]
tax[15] = [25,2]
def validate(table, first, last):
    ordered = [[lo,*table[lo]] for lo in sorted(table) if first <= lo < last]
    assert ordered[0][0] == first and ordered[-1][1] == last
    for a,b in zip(ordered,ordered[1:]): assert a[1] == b[0], (a,b)
    return ordered
tax = validate(tax,0,100000)
eicStart = text.index('2025 Earned Income Credit (EIC) Table')
eic = rows(text[eicStart:start],10)
# Page52 footnote: single/no qualifying children, 19,100 <= lookup <19,104: $0.
eic[19100] = [19104,0]
eic = validate(eic,1,19104)
output = {'sourceId':source['id'],'sourceHash':source['documentHash'],
          'taxLocator':'2025 Tax Table pp68–79, Single column',
          'eicLocator':'EIC Table pp49–52, Single/0 children column and $19,100 footnote',
          'singleTax':tax,'singleNoChildEic':eic}
encoded = json.dumps(output,indent=2)+'\n'
target=root/'single-tables.json'
if '--check' in __import__('sys').argv:
    assert target.read_text() == encoded
else: target.write_text(encoded)
print(f'{len(tax)} tax rows and {len(eic)} childless EIC rows verified')
module = '// Generated by sources/extract-tables.py from the pinned IRS PDF.\n'
module += 'export const IRS_SINGLE_TABLE_DATA = '+json.dumps(output,separators=(',',':'))+' as const;\n'
moduleTarget=root.parent/'tables-data.ts'
# Semantic comparison tolerates formatter output; JSON is the reproducibility artifact.
if '--check' not in __import__('sys').argv: moduleTarget.write_text(module)
