import {
  act,
  fireEvent,
  render,
  screen,
  waitFor,
  within,
} from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  FinanceGeneratedReportSummarySchema,
  type FinanceGeneratedReport,
} from '@emdo/contracts/browser';
import { FinanceGeneratedReports } from './finance-generated-reports.js';
import { generatedReportHtml } from './finance-generated-report-download.js';

const auth = vi.hoisted(() => ({ sessionBinding: 'current' }));
const saveFile = vi.hoisted(() => vi.fn());
vi.mock('../auth/auth-context.js', () => ({ useAuth: () => auth }));
vi.mock('../../downloads/save-memory-file.js', () => ({
  saveMemoryFile: saveFile,
}));
const id = (n: number) =>
  `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const amount = '10000000000000000000000000000.01';
const report: FinanceGeneratedReport = {
  id: id(1),
  bookId: id(2),
  workspaceId: id(3),
  automationRunId: id(4),
  reportVersion: 1,
  kind: 'posted-ledger-trial-balance',
  coverage: 'all-posted-journals-at-snapshot',
  currency: 'CAD',
  snapshotAt: '2026-09-13T12:34:56.000Z',
  rows: [
    {
      accountId: id(5),
      code: '1000',
      name: 'Cash',
      kind: 'asset',
      debit: amount,
      credit: '0',
      balance: amount,
    },
    {
      accountId: id(6),
      code: '4000',
      name: 'Income',
      kind: 'income',
      debit: '0',
      credit: amount,
      balance: `-${amount}`,
    },
  ],
  sourceJournals: [
    {
      journalId: id(7),
      effectiveOn: '2026-09-12',
      sourceReference: 'statement:September',
      payloadHash: 'a'.repeat(64),
    },
  ],
  totalDebit: amount,
  totalCredit: amount,
};
function summary(value = report) {
  return FinanceGeneratedReportSummarySchema.strip().parse(value);
}
const response = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status });
const panel = (bookId = report.bookId, role = 'viewer') => (
  <FinanceGeneratedReports bookId={bookId} bookName="Operations" role={role} />
);
async function choose() {
  fireEvent.click(
    await screen.findByRole('button', { name: /Posted ledger snapshot/ }),
  );
}
beforeEach(() => {
  auth.sessionBinding = 'current';
  saveFile.mockReset();
});
afterEach(() => vi.unstubAllGlobals());

describe('Saved accounting report library', () => {
  it('lets viewers inspect exact movements, source journals and provenance', async () => {
    const fetcher = vi.fn(async (path: string) =>
      response(
        path.includes('?')
          ? { reports: [summary()], nextOffset: null }
          : report,
      ),
    );
    vi.stubGlobal('fetch', fetcher);
    render(panel());
    await choose();
    const table = await screen.findByRole('table', {
      name: 'Gross posted movements · CAD',
    });
    expect(
      within(table).getByRole('columnheader', { name: 'Gross debit' }),
    ).toBeInTheDocument();
    expect(
      within(table).getByRole('columnheader', { name: 'Net movement' }),
    ).toBeInTheDocument();
    expect(within(table).getByText(`-${amount}`)).toBeInTheDocument();
    expect(within(table).getAllByText(amount)).toHaveLength(3);
    expect(screen.getByText(/No period filter is applied/)).toBeInTheDocument();
    expect(
      screen.getByText(
        /Saved snapshots are generated by the EMDO Finance automation leaf/,
      ),
    ).toBeInTheDocument();
    fireEvent.click(screen.getByText('Source journals'));
    fireEvent.click(screen.getByText('statement:September'));
    expect(screen.getByText('a'.repeat(64))).toBeInTheDocument();
    expect(screen.getByText('2026-09-12')).toBeInTheDocument();
    fireEvent.click(screen.getByText('Snapshot provenance'));
    expect(screen.getByText(report.automationRunId)).toBeInTheDocument();
    expect(
      screen.queryByRole('button', { name: /generate|schedule/i }),
    ).not.toBeInTheDocument();
    expect(fetcher).toHaveBeenLastCalledWith(
      `/api/v2/finance/books/${report.bookId}/reports/${report.id}`,
      expect.objectContaining({
        credentials: 'same-origin',
        cache: 'no-store',
        signal: expect.any(AbortSignal),
      }),
    );
  });

  it('paginates reports, account rows and source journals, while downloading the complete reviewed snapshot', async () => {
    const large: FinanceGeneratedReport = {
      ...report,
      totalDebit: '0',
      totalCredit: '0',
      rows: Array.from({ length: 21 }, (_, n) => ({
        accountId: id(100 + n),
        code: String(1000 + n),
        name: `Account ${n}`,
        kind: 'asset',
        debit: '0',
        credit: '0',
        balance: '0',
      })),
      sourceJournals: Array.from({ length: 21 }, (_, n) => ({
        journalId: id(200 + n),
        effectiveOn: '2026-09-12',
        sourceReference: `source:${n}`,
        payloadHash: 'a'.repeat(64),
      })),
    };
    const fetcher = vi.fn(async (path: string) =>
      response(
        path.includes('?')
          ? {
              reports: [summary(large)],
              nextOffset: path.includes('offset=0') ? 20 : null,
            }
          : large,
      ),
    );
    vi.stubGlobal('fetch', fetcher);
    render(panel());
    fireEvent.click(
      await screen.findByRole('button', { name: 'Next reports' }),
    );
    await waitFor(() =>
      expect(fetcher).toHaveBeenCalledWith(
        expect.stringContaining('offset=20&limit=20'),
        expect.anything(),
      ),
    );
    await choose();
    const table = await screen.findByRole('table');
    expect(
      within(table).queryByText('1020 · Account 20'),
    ).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Next account rows' }));
    expect(within(table).getByText('1020 · Account 20')).toBeInTheDocument();
    fireEvent.click(screen.getByText('Source journals'));
    fireEvent.click(
      screen.getByRole('button', { name: 'Next source journals' }),
    );
    expect(screen.getByText('source:20')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Download report' }));
    await waitFor(() => expect(saveFile).toHaveBeenCalledTimes(1));
    expect(saveFile).toHaveBeenCalledWith(
      `emdo-posted-ledger-${report.id}.html`,
      expect.stringContaining('source:20'),
      'text/html;charset=utf-8',
    );
    expect(saveFile.mock.calls[0]![1]).toContain('Account 0');
    expect(saveFile.mock.calls[0]![1]).toContain('Account 20');
    expect(
      fetcher.mock.calls.filter(([path]) => path.endsWith(report.id)),
    ).toHaveLength(2);
  });

  it.each([403, 503])(
    'clears old report data and blocks download when access revalidation returns %s',
    async (status) => {
      let rejected = false;
      vi.stubGlobal(
        'fetch',
        vi.fn(async (path: string) =>
          rejected
            ? response({}, status)
            : response(
                path.includes('?')
                  ? { reports: [summary()], nextOffset: null }
                  : report,
              ),
        ),
      );
      render(panel());
      await choose();
      await screen.findByRole('table');
      rejected = true;
      fireEvent.click(screen.getByRole('button', { name: 'Download report' }));
      expect(await screen.findByRole('alert')).toHaveTextContent(
        status === 403 ? 'Current book access' : 'not available',
      );
      expect(screen.queryByRole('table')).not.toBeInTheDocument();
      expect(
        screen.queryByRole('button', { name: /Posted ledger snapshot/ }),
      ).not.toBeInTheDocument();
      expect(
        screen.queryByText('No saved reports for this book'),
      ).not.toBeInTheDocument();
      expect(saveFile).not.toHaveBeenCalled();
    },
  );

  it('distinguishes an empty report library from a missing report', async () => {
    let empty = true;
    vi.stubGlobal(
      'fetch',
      vi.fn(async (path: string) =>
        path.includes('?')
          ? response({ reports: empty ? [] : [summary()], nextOffset: null })
          : response({}, 404),
      ),
    );
    render(panel());
    expect(
      await screen.findByText('No saved reports for this book'),
    ).toBeInTheDocument();
    expect(screen.queryByRole('table')).not.toBeInTheDocument();
    empty = false;
    fireEvent.click(screen.getByRole('button', { name: 'Refresh reports' }));
    await choose();
    expect(await screen.findByRole('alert')).toHaveTextContent(
      'no longer available',
    );
    expect(
      screen.getByRole('button', { name: /Posted ledger snapshot/ }),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole('button', { name: 'Download report' }),
    ).not.toBeInTheDocument();
  });

  it.each(['book', 'total'])(
    'rejects a report with invalid %s provenance or accounting integrity',
    async (invalid) => {
      vi.stubGlobal(
        'fetch',
        vi.fn(async (path: string) =>
          response(
            path.includes('?')
              ? { reports: [summary()], nextOffset: null }
              : {
                  ...report,
                  ...(invalid === 'book'
                    ? { bookId: id(99) }
                    : { totalCredit: '0' }),
                },
          ),
        ),
      );
      render(panel());
      await choose();
      expect(await screen.findByRole('alert')).toHaveTextContent(
        'could not be verified',
      );
      expect(screen.queryByRole('table')).not.toBeInTheDocument();
    },
  );

  it('aborts a pending download on book/session changes and ignores its late response', async () => {
    let release: (value: Response) => void = () => {};
    let signal: AbortSignal | undefined;
    let reads = 0;
    const fetcher = vi.fn(async (path: string, options?: RequestInit) => {
      if (path.includes('?'))
        return response({
          reports: path.includes(id(99)) ? [] : [summary()],
          nextOffset: null,
        });
      reads++;
      if (reads === 1) return response(report);
      signal = options?.signal as AbortSignal;
      return new Promise<Response>((resolve) => {
        release = resolve;
      });
    });
    vi.stubGlobal('fetch', fetcher);
    const { rerender } = render(panel());
    await choose();
    await screen.findByRole('table');
    fireEvent.click(screen.getByRole('button', { name: 'Download report' }));
    auth.sessionBinding = 'new-session';
    rerender(panel(id(99)));
    expect(signal?.aborted).toBe(true);
    await act(async () => {
      release(response(report));
    });
    expect(
      await screen.findByText('No saved reports for this book'),
    ).toBeInTheDocument();
    expect(saveFile).not.toHaveBeenCalled();
    expect(screen.queryByRole('table')).not.toBeInTheDocument();
  });

  it('does not download a snapshot that changed after the displayed review', async () => {
    let changed = false;
    vi.stubGlobal(
      'fetch',
      vi.fn(async (path: string) =>
        response(
          path.includes('?')
            ? { reports: [summary()], nextOffset: null }
            : changed
              ? {
                  ...report,
                  rows: report.rows.map((row) => ({
                    ...row,
                    name: 'Changed account name',
                  })),
                }
              : report,
        ),
      ),
    );
    render(panel());
    await choose();
    await screen.findByRole('table');
    changed = true;
    fireEvent.click(screen.getByRole('button', { name: 'Download report' }));
    expect(await screen.findByRole('alert')).toHaveTextContent(
      'could not be prepared',
    );
    expect(saveFile).not.toHaveBeenCalled();
  });

  it('escapes imported labels in the readable download while preserving exact decimals and all provenance', () => {
    const source = '<img src=x onerror=alert(1)> & "source"';
    const html = generatedReportHtml(
      {
        ...report,
        rows: report.rows.map((row) => ({
          ...row,
          name: '<script>unsafe()</script>',
        })),
        sourceJournals: [
          { ...report.sourceJournals[0]!, sourceReference: source },
        ],
      },
      '<script>book()</script>',
    );
    const document = new DOMParser().parseFromString(html, 'text/html');
    expect(document.querySelector('script, img')).toBeNull();
    expect(document.body.textContent).toContain(source);
    expect(document.body.textContent).toContain(amount);
    expect(document.body.textContent).toContain(`-${amount}`);
    expect(document.body.textContent).toContain(report.snapshotAt);
    expect(document.body.textContent).toContain(report.automationRunId);
    expect(document.body.textContent).toContain('a'.repeat(64));
  });
});
